from typing import Optional

from utils.api_client_flight import search_roundtrip_flights_from_api, search_one_way_flights_from_api


def search_one_way_flights(
    origin: str,
    destination: str,
    departure_date: Optional[str] = None,
    adults: int = 1,
    children: int = 0,
    infant_on_lap: int = 0,
    infant_in_seat: int = 0,
    cabin_class: str = "economy",
    sort_by: str = "best",
    stops: str = "0",
    alliances: Optional[str] = None,
    airlines: Optional[str] = None,
    carry_on_bag: int = 0,
    max_price: Optional[int] = None,
    emissions: int = 0,
    layover_duration: Optional[str] = None,
    airports: Optional[str] = None,
    flight_duration: Optional[str] = None,
    preferred_departure_time: Optional[str] = None,
    preferred_arrival_time: Optional[str] = None,
    time_tolerance_minutes: int = 60,
    limit: int = 10,
) -> list[dict]:
    return search_one_way_flights_from_api(
        origin=origin,
        destination=destination,
        departure_date=departure_date,
        adults=adults,
        children=children,
        infant_on_lap=infant_on_lap,
        infant_in_seat=infant_in_seat,
        cabin_class=cabin_class,
        sort_by=sort_by,
        stops=stops,
        alliances=alliances,
        airlines=airlines,
        carry_on_bag=carry_on_bag,
        max_price=max_price,
        emissions=emissions,
        layover_duration=layover_duration,
        airports=airports,
        flight_duration=flight_duration,
        preferred_departure_time=preferred_departure_time,
        preferred_arrival_time=preferred_arrival_time,
        time_tolerance_minutes=time_tolerance_minutes,
        limit=limit,
    )


def search_round_trip_flights(
    origin: str,
    destination: str,
    departure_date: Optional[str] = None,
    return_date: Optional[str] = None,
    adults: int = 1,
    children: int = 0,
    infant_on_lap: int = 0,
    infant_in_seat: int = 0,
    cabin_class: str = "economy",
    sort_by: str = "best",
    stops: str = "0",
    alliances: Optional[str] = None,
    airlines: Optional[str] = None,
    carry_on_bag: int = 0,
    max_price: Optional[int] = None,
    emissions: int = 0,
    layover_duration: Optional[str] = None,
    airports: Optional[str] = None,
    flight_duration: Optional[str] = None,
    preferred_departure_time: Optional[str] = None,
    preferred_arrival_time: Optional[str] = None,
    preferred_return_departure_time: Optional[str] = None,
    preferred_return_arrival_time: Optional[str] = None,
    time_tolerance_minutes: int = 60,
    limit: int = 2,
) -> list[dict]:
    return search_roundtrip_flights_from_api(
        origin=origin,
        destination=destination,
        departure_date=departure_date,
        return_date=return_date,
        adults=adults,
        children=children,
        infant_on_lap=infant_on_lap,
        infant_in_seat=infant_in_seat,
        cabin_class=cabin_class,
        sort_by=sort_by,
        stops=stops,
        alliances=alliances,
        airlines=airlines,
        carry_on_bag=carry_on_bag,
        max_price=max_price,
        emissions=emissions,
        layover_duration=layover_duration,
        airports=airports,
        flight_duration=flight_duration,
        preferred_departure_time=preferred_departure_time,
        preferred_arrival_time=preferred_arrival_time,
        preferred_return_departure_time=preferred_return_departure_time,
        preferred_return_arrival_time=preferred_return_arrival_time,
        time_tolerance_minutes=time_tolerance_minutes,
        limit=limit,
    )

# def get_booking_result(
#     detailToken: str,
#     adults: int = 1,
#     children: int = 0,
#     infantsOnLap: int = 0,
#     infantsInSeat: int = 0,
#     cabinClass: str = "economy",
# ) -> dict:
#     return get_booking_result_from_api(
#         detailToken=detailToken,
#         adults=adults,
#         children=children,
#         infantsOnLap=infantsOnLap,
#         infantsInSeat=infantsInSeat,
#         cabinClass=cabinClass,
#     )
